### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yousi.sjtujj-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yousi.sjtujj-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libjpomelo.so"

### ISSUE THREAD

**Issue by lxyao** [NetEase/libpomelo2#52]
02-24 11:08:20.954 13812-13812/com.yousi.sjtujj E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.yousi.sjtujj, PID: 13812
                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yousi.sjtujj-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yousi.sjtujj-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libjpomelo.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                      at java.lang.System.loadLibrary(System.java:988)
                                                                      at com.netease.pomelo.Client.<clinit>(Client.java:80)
                                                                      at com.yousi.sjtujj.ApplicationContext.onCreate(ApplicationContext.java:64)
                                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4580)
                                                                      at android.app.ActivityThread.access$1500(ActivityThread.java:154)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5283)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by cynron** [comment]
```
"/data/app/com.yousi.sjtujj-1/base.apk"],
nativeLibraryDirectories=[
/data/app/com.yousi.sjtujj-1/lib/arm64,
 /vendor/lib64, 
/system/lib64
]]] couldn't find "libjpomelo.so"
```
放的路径不对，里面给了三个路径，都没找到

**Comment by lxyao** [comment]
@cynron 在小米note3  Android 5.1.1上出的找不到，其它测试机是可以运行的

**Comment by cynron** [comment]
那就不知道了，应该找个安卓开发问一下，怎样适配

**Comment by lxyao** [comment]
@cynron  Thank you， already solve  https://github.com/yixia/VitamioBundle/issues/305

**Comment by chenlei200887** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shangliuchina.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.shangliuchina.app-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"

我是这个的问题，能帮说一下解决方案吗，实在不知道怎么改，我没有这个库
